
CC = gcc
FLAGS = -Wall -Werror -Wextra -pedantic

0-hreadelf: hreadelf.c
	$(CC) $(FLAGS) hreadelf.c -o 0-hreadelf

1-hreadelf:  hreadelf.c
	$(CC) $(FLAGS)  hreadelf.c -o 1-hreadelf
2-hreadelf: hreadelf.c
	$(CC) $(FLAGS) hreadelf.c -o 2-hreadelf

100-hreadelf: hreadelf.c
	$(CC) $(FLAGS) hreadelf.c -o 100-hreadelf
